use traluanvan;

CREATE TABLE LV_Ten (
    LV_Ma INT PRIMARY KEY,
    LV_Ten VARCHAR(1000) CHARACTER SET UTF8MB4,
    LV_TenTiengAnh VARCHAR(1000) CHARACTER SET UTF8MB4
);
CREATE TABLE LV_SVTH (
	LV_Ma INT PRIMARY KEY,
    SV1_Ten VARCHAR(50) CHARACTER SET UTF8MB4,
    MSSV1 VARCHAR(10),
    SV2_Ten VARCHAR(50) CHARACTER SET UTF8MB4,
    MSSV2 VARCHAR(10)
);
CREATE TABLE LV_GVHD (
	LV_Ma INT PRIMARY KEY,
    GV1_Ten VARCHAR(50) CHARACTER SET UTF8MB4,
    GV2_ten VARCHAR(50) CHARACTER SET UTF8MB4
);

select * from LV_Ten;
select * from LV_SVTH;
select * from LV_GVHD;

SELECT LV_Ten.LV_Ma, LV_Ten.LV_Ten, LV_Ten.LV_TenTiengAnh, LV_SVTH.SV1_Ten, LV_SVTH.MSSV1, LV_SVTH.SV2_Ten, LV_SVTH.MSSV2, LV_GVHD.GV1_Ten, LV_GVHD.GV2_Ten
FROM LV_Ten INNER JOIN LV_SVTH INNER JOIN LV_GVHD
WHERE (LV_Ten.LV_Ma = LV_SVTH.LV_Ma AND LV_Ten.LV_Ma = LV_GVHD.LV_Ma)
AND (LV_GVHD.GV1_Ten LIKE '%Xuân%' OR LV_GVHD.GV2_Ten LIKE '%Xuân%');

